export const allowedOrigins = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "https://workping.live",
    "https://www.workping.live",
    "https://admin.workping.live",
    "https://employee.workping.live",
    "https://phonepe.workping.live",
    "https://whatsapp.workping.live",
    "https://api.workping.live",
    "https://work-ping-liart.vercel.app",
    process.env.CLIENT_URL,
].filter(Boolean);
