input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  # Add filters here if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "workping-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
